export { PetSelector } from './PetSelector/PetSelector';
export { Header } from "./Header/Header";
export { Question } from "./Question/Question";
export { AgeSelector } from "./AgeSelector/AgeSelector";
export { BlockTitle } from "./BlockTitle/BlockTitle";
export { Block } from "./Block/Block";
export { AgeView } from './AgeView/AgeView'
export { BackButton } from './BackButton/BackButton'
export { Footer } from './Footer/Footer'
export { Main } from './Main/Main'
export { Input } from './Input/Input'
export { Answer } from './Answer/Answer'
export { BlockSubtitle } from './BlockSubtitle/BlockSubtitle'
export { Notifications } from './Notifications/Notifications'
export { AgeCard } from './AgeCard/AgeCard'
export * as Icons from './Icons'