export { LanguageSelect } from "./LanguageSelect/LanguageSelect";
export { PetSelector } from './PetSelector/PetSelector';
export { Header } from "./Header/Header";
export { PetCard } from "./PetCard/PetCard";
export { HeaderTitle } from "./HeaderTitle/HeaderTitle";
export { Answer } from "./Answer/Answer";
export { Question } from "./Question/Question";
export { AgeSelector } from "./AgeSelector/AgeSelector";
export { BlockTitle } from "./BlockTitle/BlockTitle";
export { Block } from "./Block/Block";
export { AgeInput } from "./AgeInput/AgeInput";
export { AgeView } from './AgeView/AgeView'
export { AgeCard } from './AgeCard/AgeCard'
export { BackButton } from './BackButton/BackButton'
export { Footer } from './Footer/Footer'
export { Main } from './Main/Main'